version: "3.8"

volumes:
  db:

networks:
  app-net:
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ${KEYCLOAK_REALM_PATH}:/opt/keycloak/data/import
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command: start-dev --import-realm
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        tag: "{{.Name}}"    

 